name: Multi Job File Share

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create files
        run: |
          echo "APP_NAME=MultiJobApp" > .env
          mkdir -p src/some
          echo "hello from job A" > src/some/test.txt

      # ðŸ”¼ Upload files
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: shared-files
          path: |
            .env
            src/some/test.txt

  use-file:
    runs-on: ubuntu-latest
    needs: create-file

    steps:
      - uses: actions/checkout@v4

      # ðŸ”½ Download files
      - name: Download files
        uses: actions/download-artifact@v4
        with:
          name: shared-files

      - name: Show files
        run: |
          echo "Root directory:"
          ls -la

          echo ""
          echo "src/some directory:"
          ls -la src/some

          echo ""
          echo "Read files:"
          cat .env
          cat src/some/test.txt
